[project]
name = "python-intermediate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.140.0",
    "python-jose>=3.5.0",
]

[tool.ruff]
line-length = 120

[tool.pyright]
venvPath = "."
venv = ".venv"
